import type { Metadata, Viewport } from "next"
import { cn } from '@/lib/utils'
import { ThemeProvider } from '@/components/theme-provider'
import "@/styles/globals.css"
import { Toaster } from '@/components/ui/toaster'
import { fontHeading, fontMono, fontSans } from '@/lib/fonts'
import { TailwindIndicator } from "@/components/tailwind-indicator"
import { Analytics } from "@/components/analytics"
import { redirect } from "next/navigation"

export const metadata: Metadata = {
  metadataBase: new URL('http://localhost:3000'),
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export const viewport: Viewport = {
  colorScheme: "dark light",
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "white" },
    { media: "(prefers-color-scheme: dark)", color: "black" },
  ],
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  return (
        <html lang="en" suppressHydrationWarning>
        <head />
        <body  
          className={cn("min-h-screen bg-background font-sans antialiased",
            fontSans.variable,
            fontMono.variable,
            fontHeading.variable
        )}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
            <TailwindIndicator />
            <Analytics />
          </ThemeProvider>
          <Toaster />
        </body>
        </html>
  )
}
